# Generated by Django 2.0 on 2019-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180303_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profile_picture',
            field=models.ImageField(default='images/staff.png', upload_to='staff_img/'),
        ),
    ]
