# Generated by Django 2.2 on 2019-05-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190520_1609'),
        ('main', '0010_auto_20190510_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Place'),
        ),
    ]
