# Generated by Django 2.0 on 2019-05-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='ImagePath',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='TelephoneNumber',
        ),
    ]
