# Generated by Django 2.0 on 2019-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20190520_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='profile_picture',
            field=models.ImageField(default='images/hotel.png', upload_to='hotel_img/'),
        ),
    ]
